services:
  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.1.3-rc.3
    command: --datadir=/data --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --http-web3provider=http://erigon:8551 --ropsten --jwt-secret=/erigon-data/jwt.hex
    ports:
      - "4000:4000"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - type: bind
        source: "${ERIGON_DATA}"
        target: /erigon-data
      - type: bind
        source: "${PRYSM_DATA}"
        target: /data
    depends_on:
      - "erigon"
  erigon:
    image: otterscan/erigon:v2022.06.03-otterscan
    command: erigon --chain=ropsten --datadir=/erigon-data --torrent.download.slots=7 --http --http.api="eth,net,web3,erigon,debug,ots,engine" --ws --http.corsdomain="*" --http.addr="0.0.0.0" --engine.addr="erigon" --http.vhosts='*'
    ports:
      - "8545:8545"
    volumes:
      - type: bind
        source: "${ERIGON_DATA}"
        target: /erigon-data
  otterscan:
    image: otterscan/otterscan:v2022.04.01-otterscan
    ports:
      - "3000:80"
    depends_on:
      - "prysm"
      - "erigon"

