services:
  erigon:
    image: otterscan/erigon:v2022.06.04-otterscan
    command: erigon --chain=sepolia --datadir=/erigon-data --torrent.download.slots=7 --http --http.api="eth,net,erigon,ots,engine" --ws --http.corsdomain="*" --http.addr="0.0.0.0" --engine.addr="erigon" --http.vhosts='*'
    ports:
      - "8545:8545"
    volumes:
      - type: bind
        source: "${ERIGON_DATA}"
        target: /erigon-data
  otterscan:
    image: otterscan/otterscan:v2022.04.01-otterscan
    ports:
      - "3000:80"
    depends_on:
      - "erigon"

