services:
  erigon:
    image: otterscan/erigon:v2022.08.03-otterscan
    command: erigon --datadir=/erigon-data --torrent.download.slots=7 --http.api="eth,net,erigon,ots" --ws --http.corsdomain="*" --http.addr="0.0.0.0" --http.vhosts='*' --authrpc.addr="erigon" --authrpc.vhosts="erigon"
    ports:
      - "8545:8545"
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "42069:42069/tcp"
      - "42069:42069/udp"
    volumes:
      - type: bind
        source: "${ERIGON_DATA}"
        target: /erigon-data
    restart: unless-stopped
    mem_swappiness: 0
  otterscan:
    image: otterscan/otterscan:v2022.04.01-otterscan
    ports:
      - "3000:80"
    depends_on:
      - "erigon"
    restart: unless-stopped
